remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
avatar: assets/logos/koi-yinyang-250.png

title: Connect.Koi
subtitle: harmony across css frameorks
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: iJungleboy of the 2sxc-team
email: info@2sxc.org
